type StyleValue = string;

const styles: Record<string, StyleValue> = {
  /* shared */
  "button": "inline-flex min-h-[42px] items-center justify-center gap-2 rounded-xl border border-transparent px-4 text-[12px] font-bold tracking-normal transition duration-150 ease-out hover:-translate-y-0.5 disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-55",
  "button-dark": "border-[#171713] bg-[#171713] text-white shadow-[0_12px_26px_rgba(23,23,19,0.14)] hover:bg-[#2b2b26] hover:shadow-[0_14px_30px_rgba(23,23,19,0.18)]",
  "button-light": "border-[#dfded7] bg-white/80 text-[#171713] shadow-[0_4px_14px_rgba(24,24,20,0.04)] hover:border-[#c9c8c0] hover:bg-white",
  "button-lime": "border-[#C8F76A] bg-[#C8F76A] text-[#171713] shadow-[0_12px_28px_rgba(200,247,106,0.18)]",
  "button-danger": "border-[#ead8d8] bg-[#faf1f1] text-[#8d5656] hover:border-[#dfc3c3] hover:bg-[#f8eaea]",
  "app-kicker": "block text-[9px] font-extrabold uppercase tracking-[0.1em] text-[#8b8c84]",
  "panel-kicker": "block text-[9px] font-extrabold uppercase tracking-[0.1em] text-[#8b8c84]",
  "language-toggle": "inline-flex min-h-[38px] min-w-[78px] items-center justify-center gap-0.5 rounded-full border border-[#d7d7cf] bg-white/90 p-[3px] text-[10px] font-bold leading-none text-[#171713] shadow-[0_5px_16px_rgba(24,24,20,0.05)] transition hover:border-[#bdbdb5] hover:bg-white hover:shadow-[0_7px_20px_rgba(24,24,20,0.08)] focus-visible:outline-2 focus-visible:outline-[#C8F76A] focus-visible:outline-offset-2 [&_span]:grid [&_span]:h-[30px] [&_span]:min-w-[33px] [&_span]:place-items-center [&_span]:rounded-full [&_span]:px-1.5 [&_span]:text-[#77786f] [&_span]:whitespace-nowrap [&_span]:transition-colors",
  "is-active": "bg-[#171713] !text-white",
  "brand-logo": "inline-flex items-center gap-2.5 font-extrabold tracking-[-0.02em]",
  "brand-logo--sm": "text-base",
  "brand-logo--md": "text-[19px]",
  "brand-logo--lg": "text-[23px]",
  "brand-logo--on-light": "text-[#141512]",
  "brand-logo--on-dark": "text-[#F7F6F1]",
  "brand-logo--mono": "text-[#141512]",
  "brand-logo__name": "leading-none",
  "brand-mark": "inline-flex shrink-0",
  "brand-mark--sm": "h-7 w-7",
  "brand-mark--md": "h-8 w-8",
  "brand-mark--lg": "h-10 w-10",
  "brand-mark--on-light": "[&_.brand-mark__bg]:fill-[#141512] [&_.brand-mark__bookmark]:fill-[#F7F6F1] [&_.brand-mark__accent]:fill-[#C8F76A]",
  "brand-mark--on-dark": "[&_.brand-mark__bg]:fill-[#F7F6F1] [&_.brand-mark__bookmark]:fill-[#141512] [&_.brand-mark__accent]:fill-[#C8F76A]",
  "brand-mark--mono": "[&_.brand-mark__bg]:fill-[#141512] [&_.brand-mark__bookmark]:fill-[#F7F6F1] [&_.brand-mark__accent]:fill-[#F7F6F1]",

  "auth-shell": "flex min-h-screen w-full flex-col overflow-x-hidden bg-[radial-gradient(circle_at_12%_8%,rgba(200,247,106,0.16),transparent_24rem),radial-gradient(circle_at_88%_18%,rgba(219,232,255,0.24),transparent_28rem),#f7f6f2] px-5 pb-[22px] pt-[18px]",
  "auth-topbar": "mx-auto flex min-h-[42px] w-full max-w-[1180px] items-center justify-between gap-5",
  "auth-content": "mx-auto flex w-full max-w-[1180px] flex-1 items-start justify-center px-0 pb-[18px] pt-[clamp(22px,4vh,48px)]",
  "auth-card": "w-[min(100%,620px)] rounded-[32px] border border-black/[0.07] bg-white/90 p-[clamp(28px,4vw,46px)] shadow-[0_22px_65px_rgba(26,25,20,0.1)] backdrop-blur [&>h1]:m-0 [&>h1]:max-w-[570px] [&>h1]:text-[clamp(44px,6.2vw,64px)] [&>h1]:leading-[0.99] [&>h1]:tracking-normal [&>h1]:text-[#171713] [&>p]:mt-[17px] [&>p]:max-w-[560px] [&>p]:text-[clamp(15px,2vw,17px)] [&>p]:leading-[1.58] [&>p]:text-[#6f7068]",
  "auth-eyebrow": "mb-4 inline-flex items-center text-[9px] font-extrabold uppercase tracking-[0.11em] text-[#77786f]",
  "auth-footer": "mt-4 text-center text-[10px] text-[#96978f]",
  "auth-form": "mt-7 flex flex-col gap-4 [&_label]:grid [&_label]:gap-2 [&_label>span]:text-[13px] [&_label>span]:font-bold [&_input]:min-h-[58px] [&_input]:rounded-2xl [&_input]:border [&_input]:border-[#d9d7cf] [&_input]:bg-white [&_input]:px-[17px] [&_input]:text-base [&_input]:text-[#171713] [&_input]:outline-none [&_input]:transition [&_input]:placeholder:text-[#9a9b93] [&_input]:focus:border-[#a9aaa3] [&_input]:focus:ring-4 [&_input]:focus:ring-[#C8F76A22]",
  "auth-primary-social": "w-full",
  "auth-google-button": "grid min-h-[62px] w-full grid-cols-[42px_minmax(0,1fr)_42px] items-center gap-2 rounded-2xl border border-[#d9d7cf] bg-white px-3.5 text-[#171713] shadow-[0_10px_28px_rgba(23,23,19,0.05)] transition hover:-translate-y-px hover:border-[#bbb9b0] hover:shadow-[0_14px_34px_rgba(23,23,19,0.08)] focus-visible:outline-2 focus-visible:outline-[#C8F76A] focus-visible:outline-offset-2 disabled:cursor-wait disabled:opacity-55 disabled:hover:translate-y-0",
  "auth-google-button__icon": "grid h-9 w-9 place-items-center justify-self-start rounded-[11px] border border-[#e2e0d8] bg-[#fafaf7]",
  "auth-google-button__copy": "flex min-w-0 flex-col items-center justify-center gap-0.5 text-center [&_strong]:text-[14px] [&_strong]:font-extrabold [&_strong]:leading-[1.25] [&_small]:text-[11px] [&_small]:leading-[1.35] [&_small]:text-[#878880]",
  "auth-google-button__arrow": "justify-self-end text-xl leading-none text-[#777870] transition-transform group-hover:translate-x-0.5",
  "auth-divider": "my-0.5 flex items-center gap-3.5 text-[11px] text-[#96978f] before:h-px before:flex-1 before:bg-[#e4e3dc] after:h-px after:flex-1 after:bg-[#e4e3dc]",
  "auth-fields": "flex flex-col gap-4",
  "auth-message": "rounded-xl px-3 py-2.5 text-[11px] leading-relaxed",
  "auth-message--error": "border border-[#ead8d8] bg-[#faf1f1] text-[#7d4d4d]",
  "auth-message--success": "border border-[#d6e6c8] bg-[#eef7e9] text-[#4e6b3c] [&_p]:mt-1.5",
  "auth-submit": "min-h-[58px] rounded-2xl text-[15px]",
  "auth-link": "text-[12px] font-semibold text-[#6f7068] underline-offset-4 hover:text-[#171713] hover:underline",
  "auth-link--center": "mt-[-1px] text-center",
  "auth-switch": "mt-px text-center text-[12px] text-[#77786f] [&_a]:font-bold [&_a]:text-[#171713] [&_a]:hover:underline",
  "app-shell": "flex min-h-screen bg-[#f7f6f2] max-[760px]:block",
  "app-sidebar": "sticky top-0 flex h-screen w-[230px] shrink-0 flex-col border-r border-[#dfded7] bg-white/88 px-[18px] py-5 backdrop-blur max-[760px]:hidden",
  "app-sidebar__brand": "mb-5 inline-flex px-1 py-1",
  "app-sidebar__workspace": "mb-4 rounded-xl bg-[#f4f4ef] px-3 py-2.5 [&_span]:text-[9px] [&_span]:font-extrabold [&_span]:uppercase [&_span]:tracking-[0.1em] [&_span]:text-[#8b8c84]",
  "app-sidebar__bottom": "mt-auto space-y-3",
  "user-chip": "flex min-w-0 items-center gap-2 rounded-xl border border-[#e6e5de] bg-[#fafaf7] px-2.5 py-2",
  "user-chip__avatar": "grid h-8 w-8 shrink-0 place-items-center rounded-[10px] bg-[#171713] text-xs font-extrabold text-white",
  "user-chip__email": "min-w-0 truncate text-[10px] text-[#6f7068]",
  "signout-button": "inline-flex min-h-9 w-full items-center justify-center gap-2 rounded-xl border border-transparent bg-transparent px-2 text-[11px] font-semibold text-[#6f7068] transition hover:border-[#dfded7] hover:bg-[#f5f5f1] hover:text-[#171713] disabled:cursor-wait disabled:opacity-50",
  "app-main": "min-w-0 flex-1",
  "app-topbar": "sticky top-0 z-40 flex min-h-[68px] items-center justify-between gap-4 border-b border-[#dfded7] bg-[#f7f6f2]/90 px-8 backdrop-blur max-[760px]:min-h-[56px] max-[760px]:gap-2 max-[760px]:px-[14px]",
  "app-content": "mx-auto w-full max-w-[1180px] px-8 py-7 md:px-8 max-[760px]:px-[14px] max-[760px]:py-[22px] max-[760px]:pb-[92px]",
  "app-nav": "flex flex-col gap-1",
  "app-nav--mobile": "fixed inset-x-3 bottom-3 z-50 grid grid-cols-4 gap-1 rounded-2xl border border-[#dfded7] bg-white/95 p-1.5 shadow-[0_18px_40px_rgba(23,23,19,0.14)] backdrop-blur md:hidden [&_.app-nav__item]:min-h-12 [&_.app-nav__item]:justify-center [&_.app-nav__item]:gap-0.5 [&_.app-nav__item]:px-1 [&_.app-nav__item]:py-1 [&_.app-nav__item]:flex-col [&_.app-nav__item]:text-[9px] max-[760px]:bottom-[calc(12px+env(safe-area-inset-bottom))]",
  "app-nav__item": "relative flex items-center gap-2.5 rounded-xl px-3 py-2.5 text-[11px] font-bold text-[#86877f] transition hover:bg-[#f5f5f1] hover:text-[#171713] [&.active]:bg-[#171713] [&.active]:text-white",
  "active": "active",
  "app-header": "mb-6 flex items-start justify-between gap-5 [&_h1]:m-0 [&_h1]:text-[clamp(30px,4vw,42px)] [&_h1]:font-extrabold [&_h1]:tracking-normal [&_p]:m-0 max-[760px]:flex-wrap max-[760px]:items-end",
  "dashboard-header": "",
  "dashboard-header__subtitle": "mt-2 max-w-[650px] text-[13px] leading-7 text-[#77786f]",
  "app-header__actions": "flex shrink-0 items-center gap-2",
  "app-add-button": "min-h-10 rounded-xl",
  "page-back-link": "mb-2 inline-flex items-center text-[11px] font-semibold text-[#85867e] transition hover:text-[#171713]",
  "app-page-header": "mb-6 flex items-end justify-between gap-5 [&>div:first-child]:min-w-0 [&_h1]:m-0 [&_h1]:mt-1.5 [&_h1]:text-[clamp(30px,4vw,40px)] [&_h1]:font-extrabold [&_h1]:tracking-normal [&_p]:mt-2 [&_p]:text-[12px] [&_p]:leading-relaxed [&_p]:text-[#7c7d74] max-[760px]:flex-wrap max-[760px]:items-end",
  "app-page-header__action": "shrink-0 max-[760px]:w-full",
  "command-trigger": "inline-flex min-h-10 min-w-[250px] items-center justify-between gap-3 rounded-xl border border-[#dfded7] bg-white/80 px-3 text-[11px] text-[#8a8b82] shadow-[0_3px_12px_rgba(24,24,20,0.03)] hover:border-[#c9c8c0] hover:bg-white focus-visible:outline-2 focus-visible:outline-[#C8F76A] focus-visible:outline-offset-2 [&_kbd]:rounded-md [&_kbd]:bg-[#f1f1ed] [&_kbd]:px-1.5 [&_kbd]:py-1 [&_kbd]:text-[9px] max-[760px]:min-w-0 max-[760px]:flex-1 max-[760px]:w-auto max-[760px]:max-w-none",
  "command-trigger__search": "inline-flex min-w-0 items-center gap-2 truncate",
  "command-overlay": "fixed inset-0 z-[100] grid place-items-start bg-black/30 px-4 pt-[14vh] backdrop-blur-[2px]",
  "command-dialog": "w-full max-w-[620px] overflow-hidden rounded-2xl border border-[#dfded7] bg-white shadow-[0_30px_80px_rgba(23,23,19,0.2)]",
  "command-input-wrap": "flex min-h-14 items-center gap-3 border-b border-[#e6e5de] px-4 [&_input]:min-w-0 [&_input]:flex-1 [&_input]:border-0 [&_input]:bg-transparent [&_input]:text-sm [&_input]:outline-none [&_input]:ring-0 [&_input]:placeholder:text-[#a0a19a] [&_kbd]:text-[9px] [&_kbd]:text-[#8a8b82]",
  "command-list": "max-h-[360px] overflow-y-auto p-1.5",
  "command-item": "flex w-full items-center gap-3 rounded-xl border-0 bg-transparent px-3 py-2.5 text-left transition hover:bg-[#f4f4ef] focus-visible:bg-[#f4f4ef] [&.selected]:bg-[#eef5e8]",
  "command-item__icon": "grid h-8 w-8 shrink-0 place-items-center rounded-[9px] bg-[#f4f4ef] text-[#6f7068]",
  "command-item__label": "min-w-0 flex-1 truncate text-[12px] font-semibold text-[#171713]",
  "command-empty": "m-0 px-3 py-10 text-center text-[12px] text-[#8a8b82]",
  "command-footer": "flex flex-wrap gap-4 border-t border-[#e6e5de] px-4 py-2.5 text-[9px] text-[#8a8b82] [&_kbd]:rounded bg-[#f4f4ef] [&_kbd]:px-1",
  "loading-skeleton": "animate-pulse rounded-xl bg-[#e7e6df]",
  "loading-skeleton--title": "h-8 w-2/5",
  "loading-skeleton--line": "mt-3 h-4 w-1/2",
  "loading-skeleton--panel": "mt-6 h-44 w-full",
  "loading-skeleton-list": "mt-3 space-y-2",
  "loading-skeleton--row": "h-16 w-full",
  /* dashboard */
  "attention-panel": "rounded-2xl border border-[#dfded7] bg-white p-5 shadow-[0_10px_28px_rgba(23,23,19,0.04)]",
  "dashboard-hero": "relative mb-5 grid min-h-[245px] grid-cols-[minmax(0,1fr)_160px] overflow-hidden rounded-[22px] bg-[#171713] p-7 text-[#f7f6f2] shadow-[0_20px_55px_rgba(23,23,19,0.12)] max-[760px]:grid-cols-1 max-[760px]:min-h-0 max-[760px]:p-5",
  "dashboard-hero--empty": "min-h-[220px]",
  "dashboard-hero__grain": "pointer-events-none absolute inset-0 opacity-60 [background-image:radial-gradient(circle_at_20%_20%,rgba(200,247,106,0.1),transparent_25rem),radial-gradient(circle_at_90%_70%,rgba(219,232,255,0.08),transparent_22rem)]",
  "dashboard-hero__copy": "relative z-10 self-center [&_h2]:m-0 [&_h2]:max-w-[620px] [&_h2]:text-[clamp(32px,4vw,54px)] [&_h2]:font-extrabold [&_h2]:tracking-normal [&_p]:mt-3 [&_p]:max-w-[560px] [&_p]:text-[13px] [&_p]:leading-7 [&_p]:text-[#b8b8af]",
  "dashboard-hero__meta": "mt-3 flex flex-wrap items-center gap-2 text-[10px] text-[#b1b1a8]",
  "dashboard-hero__amount": "mt-5 block text-[26px] font-extrabold tracking-normal",
  "dashboard-hero__link": "mt-5 inline-flex items-center gap-2 text-[11px] font-bold text-[#C8F76A] hover:underline",
  "dashboard-hero__mark": "relative z-10 ml-auto grid h-[145px] w-[145px] place-self-center place-items-center rounded-[38px] bg-white/[0.05] [&_span]:block [&_span]:h-12 [&_span]:w-2.5 [&_span]:rounded-full [&_span:nth-child(1)]:bg-[#6e755e] [&_span:nth-child(2)]:h-16 [&_span:nth-child(2)]:bg-[#95a47c] [&_span:nth-child(3)]:h-20 [&_span:nth-child(3)]:bg-[#C8F76A] max-[760px]:hidden",
  "recent-panel": "overflow-hidden rounded-2xl border border-[#dfded7] bg-white",
  "recent-panel--spaced": "mt-[42px] max-[760px]:mt-[34px]",
  "recent-panel__empty": "flex flex-col gap-1 border-t border-[#e6e5de] px-5 py-[18px] [&_strong]:text-[13px] [&_span]:text-[12px] [&_span]:text-[#6f7068]",
  "dashboard-attention-panel": "",
  "recent-panel__heading": "flex min-h-[72px] items-center justify-between gap-4 border-b border-[#e6e5de] px-5 py-3.5 [&>div]:min-w-0 [&_h2]:m-0 [&_h2]:mt-1 [&_h2]:text-[17px] [&_h2]:font-extrabold [&_h2]:tracking-normal",
  "dashboard-purchase-list": "divide-y divide-[#e8e7e1]",
  "dashboard-purchase-row": "group grid min-h-[72px] grid-cols-[36px_minmax(0,1fr)_auto_auto] items-center gap-3 px-5 py-3.5 transition hover:bg-[#fafaf7] [&>.purchase-meta]:min-w-0 max-[760px]:grid-cols-[36px_minmax(0,1fr)_auto] max-[760px]:gap-2.5 max-[760px]:px-3",
  "dashboard-purchase-amount": "text-[12px] font-bold text-[#171713]",
  "dashboard-row-chevron": "text-[#8a8b82] transition group-hover:translate-x-0.5 max-[760px]:hidden",
  "dashboard-inline-note": "flex items-center justify-between gap-4 border-t border-[#e6e5de] px-5 py-4 text-[11px] text-[#77786f] [&_a]:font-bold [&_a]:text-[#171713]",
  /* purchase base */
  "purchases-section": "space-y-4",
  "purchase-search": "grid grid-cols-[minmax(0,1fr)_auto_auto] gap-2.5 rounded-2xl border border-[#dfded7] bg-white p-4 shadow-[0_8px_22px_rgba(23,23,19,0.035)] [&>input[name=q]]:min-h-11 [&>input[name=q]]:min-w-0 [&>input[name=q]]:rounded-xl [&>input[name=q]]:border [&>input[name=q]]:border-[#d4d3cc] [&>input[name=q]]:bg-white [&>input[name=q]]:px-3.5 [&>input[name=q]]:text-[13px] [&>input[name=q]]:text-[#171713] [&>input[name=q]]:outline-none [&>input[name=q]]:focus:border-[#a9aaa3] [&>input[name=q]]:focus:ring-4 [&>input[name=q]]:focus:ring-[#C8F76A22] max-[760px]:grid-cols-1",
  "purchase-search__filters": "col-span-full grid grid-cols-5 items-end gap-2.5 max-[1100px]:grid-cols-3 max-[760px]:grid-cols-1 [&_label]:grid [&_label]:min-w-0 [&_label]:gap-1.5 [&_label>span]:text-[11px] [&_label>span]:font-bold [&_label>span]:text-[#4f5049] [&_input:not([type=checkbox])]:min-h-11 [&_input:not([type=checkbox])]:w-full [&_input:not([type=checkbox])]:rounded-xl [&_input:not([type=checkbox])]:border [&_input:not([type=checkbox])]:border-[#d4d3cc] [&_input:not([type=checkbox])]:bg-white [&_input:not([type=checkbox])]:px-3 [&_input:not([type=checkbox])]:text-[12px] [&_input:not([type=checkbox])]:text-[#171713] [&_input:not([type=checkbox])]:outline-none [&_input:not([type=checkbox])]:focus:border-[#a9aaa3] [&_input:not([type=checkbox])]:focus:ring-4 [&_input:not([type=checkbox])]:focus:ring-[#C8F76A22]",
  "purchase-search__checks": "col-span-full flex flex-wrap gap-4 border-t border-[#e6e5de] pt-3 text-[10px] text-[#6f7068] [&_label]:inline-flex [&_label]:items-center [&_label]:gap-1.5 grid grid-cols-[repeat(3,max-content)] items-center gap-x-5 gap-y-2 border-t border-[#e6e5de] pt-3 text-[10px] text-[#6f7068] [&_label]:inline-flex [&_label]:w-fit [&_label]:items-center [&_label]:gap-1.5 [&_input]:m-0 [&_input]:shrink-0 [&_input[type=checkbox]]:!h-4 [&_input[type=checkbox]]:!w-4 [&_input[type=checkbox]]:!shrink-0 [&_input[type=checkbox]]:accent-[#171713] max-[760px]:grid-cols-1 max-[760px]:gap-2.5",
  "purchase-results": "overflow-hidden rounded-2xl border border-[#dfded7] bg-white",
  "purchase-result": "group grid min-h-[72px] grid-cols-[38px_minmax(0,1fr)_auto_auto] items-center gap-3 border-b border-[#e8e7e1] px-4 py-3.5 last:border-b-0 hover:bg-[#fafaf7] max-[760px]:grid-cols-[38px_minmax(0,1fr)_auto] max-[760px]:gap-2.5 max-[760px]:px-3",
  "purchase-result__icon": "grid h-10 w-10 place-items-center rounded-xl bg-[#dbe8ff] text-[12px] font-extrabold text-[#2e3027]",
  "purchase-result__icon--large": "h-[52px] w-[52px] rounded-2xl text-[16px]",
  "purchase-result__body": "min-w-0 [&_strong]:block [&_strong]:truncate [&_strong]:text-[12px] [&_strong]:font-bold [&_span]:mt-1 [&_span]:block [&_span]:truncate [&_span]:text-[10px] [&_span]:text-[#85867e]",
  "purchase-result__amount": "text-[12px] font-extrabold text-[#171713] max-[760px]:col-start-3 max-[760px]:row-start-1",
  "purchase-result__chevron": "text-[#8a8b82] transition group-hover:translate-x-0.5 max-[760px]:hidden",
  "purchase-empty": "grid min-h-[320px] place-items-center content-center gap-2 rounded-2xl border border-[#dfded7] bg-white p-8 text-center [&_h2]:m-0 [&_h2]:text-xl [&_h2]:font-extrabold [&_p]:m-0 [&_p]:max-w-[420px] [&_p]:text-[12px] [&_p]:leading-6 [&_p]:text-[#77786f]",
  "purchase-icon": "grid h-[37px] w-[37px] shrink-0 place-items-center rounded-xl font-extrabold text-[#2e3027]",
  "purchase-blue": "bg-[#dbe8ff]",
  "purchase-amber": "bg-[#f7e6bd]",
  "purchase-violet": "bg-[#e7dcff]",
  "purchase-meta": "flex min-w-0 flex-col gap-[3px] [&_strong]:truncate [&_strong]:text-[12px] [&_span]:truncate [&_span]:text-[10px] [&_span]:text-[#85867e]",
  "empty-icon": "grid h-10 w-10 place-items-center rounded-xl bg-[#f3f3ee] text-lg text-[#8a8b82]",
  "purchase-editor": "mx-auto w-full max-w-[760px]",
  "purchase-form": "grid gap-4 rounded-[22px] border border-[#dfded7] bg-white p-6 shadow-[0_14px_35px_rgba(23,23,19,0.06)] [&>label]:min-w-0 [&>label]:space-y-1.5 [&>label>span]:block [&>label>span]:text-[11px] [&>label>span]:font-bold [&_input:not([type=checkbox])]:min-h-11 [&_input:not([type=checkbox])]:w-full [&_input:not([type=checkbox])]:rounded-lg [&_input:not([type=checkbox])]:border [&_input:not([type=checkbox])]:border-[#d4d3cc] [&_input:not([type=checkbox])]:bg-white [&_input:not([type=checkbox])]:px-3 [&_input:not([type=checkbox])]:text-[12px] [&_input:not([type=checkbox])]:text-[#171713] [&_input:not([type=checkbox])]:outline-none [&_input:not([type=checkbox])]:focus:border-[#a9aaa3] [&_input:not([type=checkbox])]:focus:ring-4 [&_input:not([type=checkbox])]:focus:ring-[#C8F76A22] [&_textarea]:min-h-[110px] [&_textarea]:w-full [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-[#d4d3cc] [&_textarea]:bg-white [&_textarea]:p-3 [&_textarea]:text-[12px] [&_textarea]:outline-none [&_textarea]:focus:border-[#a9aaa3] [&_textarea]:focus:ring-4 [&_textarea]:focus:ring-[#C8F76A22] [&_em]:not-italic [&_em]:font-normal [&_em]:text-[#8a8b82]",
  "purchase-form-grid": "grid grid-cols-2 gap-2.5 max-[720px]:grid-cols-1",
  "money-input": "flex items-center overflow-hidden rounded-lg border border-[#d4d3cc] bg-white focus-within:border-[#a9aaa3] focus-within:ring-4 focus-within:ring-[#C8F76A22] [&>span]:px-3 [&>span]:text-[#8a8b82] [&_input]:border-0 [&_input]:focus:ring-0",
  "field-error": "block text-[9px] text-[#8f5959]",
  "field-hint": "block text-[9px] leading-5 text-[#8a8b82]",
  "purchase-form-proof-note": "grid gap-1 rounded-xl border border-[#dce7d3] bg-[#f1f8eb] p-3 [&_strong]:text-[11px] [&_span]:text-[10px] [&_span]:text-[#6f7b66]",
  "purchase-submit": "min-h-11",
  "purchase-editor-cancel": "mt-3 inline-flex text-[11px] font-semibold text-[#77786f] hover:text-[#171713] hover:underline",
  "purchase-detail": "overflow-hidden rounded-2xl border border-[#dfded7] bg-white",
  "purchase-detail__hero": "flex items-center gap-4 border-b border-[#e6e5de] px-6 py-5 [&_h2]:m-1.5 [&_h2]:text-2xl [&_h2]:font-extrabold [&_h2]:tracking-normal [&_strong]:block [&_strong]:mt-1 [&_strong]:text-xl [&_strong]:font-extrabold max-[520px]:items-start max-[520px]:gap-3 max-[520px]:px-4 max-[520px]:py-4 max-[520px]:[&_h2]:text-xl",
  "purchase-detail__grid": "grid grid-cols-4 divide-x divide-[#e6e5de] max-[820px]:grid-cols-2 max-[520px]:grid-cols-1",
  "detail-cell": "min-w-0 p-5 [&_span]:block [&_span]:text-[9px] [&_span]:font-bold [&_span]:uppercase [&_span]:tracking-[0.08em] [&_span]:text-[#8a8b82] [&_strong]:mt-2 [&_strong]:block [&_strong]:truncate [&_strong]:text-[12px]",
  "purchase-detail__section": "border-t border-[#e6e5de] p-6 [&>small]:block [&>small]:mt-2 [&>small]:text-[9px] [&>small]:text-[#8a8b82] max-[520px]:p-4",
  "purchase-note": "mt-2 whitespace-pre-wrap text-[12px] leading-6 text-[#4e4f48]",
  "purchase-note--empty": "text-[#9a9b93]",
  "purchase-detail__actions": "flex flex-wrap justify-end gap-2.5 pt-4 max-[640px]:flex-col max-[640px]:[&>*]:w-full",
  "purchase-documents": "mt-5 rounded-2xl border border-[#dfded7] bg-white p-5",
  "purchase-documents__header": "mb-4 [&_p]:mt-1.5 [&_p]:max-w-[640px] [&_p]:text-[11px] [&_p]:leading-6 [&_p]:text-[#77786f]",
  "purchase-documents__uploader": "rounded-xl border border-dashed border-[#cfcfc7] bg-[#fafaf7] p-4",
  "purchase-documents__controls": "grid grid-cols-2 gap-3 max-[720px]:grid-cols-1 [&_label]:grid [&_label]:gap-1.5 [&_label>span]:text-[10px] [&_label>span]:font-bold",
  "purchase-documents__upload-row": "mt-3 flex items-center justify-between gap-3 rounded-lg bg-white px-3 py-2.5 text-[10px] text-[#77786f] [&>span]:min-w-0 [&>span]:break-words max-[640px]:flex-col max-[640px]:items-stretch max-[640px]:gap-2",
  "document-status": "mt-3 rounded-lg border border-[#d6e6c8] bg-[#eef7e9] px-3 py-2 text-[10px] text-[#4e6b3c]",
  "document-error": "mt-3 rounded-lg border border-[#ead8d8] bg-[#faf1f1] px-3 py-2 text-[10px] text-[#7d4d4d]",
  "purchase-document-list": "mt-4 divide-y divide-[#e6e5de] rounded-xl border border-[#e6e5de] bg-white",
  "purchase-document-row": "grid grid-cols-[40px_minmax(0,1fr)_auto] items-center gap-3 px-3.5 py-3 max-[760px]:grid-cols-[40px_minmax(0,1fr)] max-[760px]:gap-2.5",
  "purchase-document-row__icon": "grid h-9 w-9 place-items-center rounded-lg bg-[#f3f3ee] text-[8px] font-extrabold text-[#77786f]",
  "purchase-document-row__body": "min-w-0 [&_strong]:block [&_strong]:truncate [&_strong]:text-[11px] [&_span]:mt-1 [&_span]:block [&_span]:text-[9px] [&_span]:text-[#8a8b82]",
  "purchase-document-row__actions": "flex items-center gap-1.5 justify-end max-[760px]:col-span-full max-[640px]:w-full max-[640px]:[&_a]:flex-1 max-[640px]:[&_button]:flex-1",
  "purchase-documents__empty": "m-0 mt-4 rounded-xl bg-[#fafaf7] px-4 py-8 text-center text-[10px] text-[#8a8b82]",
  /* extras */
  "purchase-extras": "mt-5 space-y-4 rounded-2xl border border-[#dfded7] bg-white p-5",
  "purchase-extras__block": "rounded-xl border border-[#e6e5de] p-4 [&>h3]:m-0 [&>h3]:mb-3 [&>h3]:text-[12px] [&>h3]:font-extrabold [&>p]:m-0 [&>p]:text-[11px] [&>p]:leading-6 [&>p]:text-[#77786f]",
  "purchase-extra-row": "flex items-center justify-between gap-3 border-t border-[#ecebe5] py-3 first:border-t-0 [&>div:first-child]:min-w-0 [&_strong]:block [&_strong]:truncate [&_strong]:text-[11px] [&_span]:mt-1 [&_span]:block [&_span]:truncate [&_span]:text-[9px] [&_span]:text-[#8a8b82]",
  "purchase-extras__form": "mt-3 grid grid-cols-6 gap-2 max-[900px]:grid-cols-2 max-[520px]:grid-cols-1 [&>*]:min-w-0 [&_input]:min-w-0",
  /* reminders */
  "reminders-layout": "grid grid-cols-[minmax(0,1.08fr)_minmax(320px,0.72fr)] items-start gap-8 max-[900px]:grid-cols-1",
  "reminder-header-count": "inline-flex min-h-8 items-center rounded-full border border-[#dfded7] bg-white px-2.5 text-[10px] font-bold text-[#6f7068]",
  "reminder-page-message": "mb-4 text-[11px] text-[#6f7068]",
  "reminder-list-panel": "overflow-hidden rounded-2xl border border-[#dfded7] bg-white",
  "reminder-list-panel__heading": "flex min-h-[70px] items-center justify-between gap-4 border-b border-[#e6e5de] px-[18px] py-4 [&_h2]:m-1 [&_h2]:text-[18px] [&_h2]:font-extrabold [&_h2]:tracking-normal",
  "reminder-count": "grid h-7 min-w-7 place-items-center rounded-lg bg-[#f1f1ed] px-1.5 text-[9px] font-extrabold tabular-nums text-[#6f7068]",
  "reminder-group": "px-[18px] pt-[18px] last:pb-[18px] [&>h3]:m-0 [&>h3]:mb-2 [&>h3]:text-[9px] [&>h3]:font-extrabold [&>h3]:uppercase [&>h3]:tracking-[0.1em] [&>h3]:text-[#9a9b93]",
  "reminder-rows": "border-t border-[#e6e5de]",
  "reminder-row": "grid min-h-[76px] grid-cols-[34px_minmax(0,1fr)_auto] items-center gap-3 border-b border-[#e6e5de] py-3 last:border-b-0",
  "reminder-row--completed": "opacity-55",
  "reminder-row__mark": "grid h-[30px] w-[30px] place-items-center rounded-lg border border-[#dfded7] bg-[#f8f8f5] text-[#6f7068]",
  "reminder-row__body": "min-w-0",
  "reminder-row__title": "flex min-w-0 flex-wrap items-center gap-2 [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[12px] [&_strong]:tracking-normal",
  "reminder-type": "inline-flex min-h-[18px] items-center rounded border border-[#dfded7] bg-[#fafaf7] px-1.5 text-[8px] font-bold text-[#8a8b82]",
  "reminder-row__meta": "mt-1 block truncate text-[10px] text-[#6f7068]",
  "reminder-row__due": "mt-0.5 block truncate text-[9px] font-bold text-[#171713]",
  "reminder-row__actions": "inline-flex items-center gap-1",
  "reminder-icon-button": "grid h-[30px] w-[30px] place-items-center rounded-lg border border-transparent bg-transparent text-[#6f7068] hover:border-[#dfded7] hover:bg-[#f3f3f0] hover:text-[#171713] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#d7efbd]",
  "reminder-icon-button--danger": "hover:border-[#ead8d8] hover:bg-[#faf1f1] hover:text-[#8d5656]",
  "reminder-empty": "grid min-h-[280px] place-items-center content-center px-6 py-11 text-center",
  "reminder-empty__icon": "grid h-10 w-10 place-items-center rounded-xl border border-[#dfded7] bg-[#f8f8f5] text-[#6f7068]",
  "reminder-form-panel": "sticky top-[78px] rounded-2xl border border-[#dfded7] bg-white max-[900px]:static",
  "reminder-form-panel__heading": "flex min-h-[70px] items-center justify-between gap-4 border-b border-[#e6e5de] px-[18px] py-4 [&_h2]:m-1 [&_h2]:text-[18px] [&_h2]:font-extrabold]",
  "reminder-form": "grid gap-3.5 p-[18px] [&>label]:mb-0 [&>label]:space-y-1.5 [&_label>span]:block [&_label>span]:text-[10px] [&_label>span]:font-bold [&_input:not([type=checkbox])]:min-h-10 [&_input:not([type=checkbox])]:w-full [&_input:not([type=checkbox])]:rounded-lg [&_input:not([type=checkbox])]:border [&_input:not([type=checkbox])]:border-[#d4d3cc] [&_input:not([type=checkbox])]:bg-white [&_input:not([type=checkbox])]:px-2.5 [&_input:not([type=checkbox])]:text-[11px] [&_input:not([type=checkbox])]:outline-none [&_textarea]:w-full [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-[#d4d3cc] [&_textarea]:bg-white [&_textarea]:p-2.5 [&_textarea]:text-[11px] [&_textarea]:outline-none [&_input:not([type=checkbox])]:focus:border-[#a9aaa3] [&_textarea]:focus:border-[#a9aaa3] [&_input:not([type=checkbox])]:focus:ring-4 [&_textarea]:focus:ring-4 [&_input:not([type=checkbox])]:focus:ring-[#C8F76A22] [&_textarea]:focus:ring-[#C8F76A22]",
  "reminder-form-grid": "grid grid-cols-[0.82fr_1.18fr] gap-2.5 max-[760px]:grid-cols-1",
  "reminder-offsets": "grid grid-cols-3 gap-1.5",
  "reminder-offset": "inline-flex min-h-9 items-center gap-2 rounded-lg border border-[#dfded7] bg-[#fafaf7] px-2 text-[9px] text-[#6f7068] [&:has(input:checked)]:border-[#cadbb8] [&:has(input:checked)]:bg-[#f0f6e8] [&:has(input:checked)]:text-[#171713]",
  "reminder-enabled": "inline-flex items-center gap-2 text-[10px] text-[#6f7068]",
  "reminder-field-error": "block text-[9px] text-[#8f5959]",
  "reminder-message": "mb-1 rounded-lg px-2.5 py-2.5 text-[10px] leading-5",
  "reminder-message--error": "border border-[#ead8d8] bg-[#faf1f1] text-[#7d4d4d]",
  "reminder-form__actions": "flex justify-end gap-1.5 pt-0.5",
  "reminder-cancel": "min-h-8 px-2.5 text-[9px]",
  "reminder-form__hint": "m-0 text-[10px] leading-6 text-[#6f7068]",
  "notification-settings": "mb-5 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 rounded-2xl border border-[#dfded7] bg-white p-5 max-[700px]:grid-cols-1 [&_h2]:m-1 [&_h2]:text-[15px] [&_h2]:font-extrabold [&_p]:m-1 [&_p]:text-[10px] [&_p]:leading-5 [&_p]:text-[#77786f]",
  "notification-settings__message": "col-span-full m-0 text-[10px] text-[#6f7068]",
  /* landing */
  "landing-shell": "overflow-hidden bg-[#141512] font-sans text-[#F7F6F1]",
  "landing-container": "mx-auto w-[min(1160px,calc(100%-32px))]",
  "landing-nav-wrap": "absolute inset-x-0 top-0 z-30",
  "landing-nav": "mx-auto flex min-h-[76px] w-[min(1160px,calc(100%-32px))] items-center justify-between gap-5 border-b border-white/10",
  "landing-brand": "inline-flex items-center gap-2.5 font-extrabold tracking-[-0.02em] text-[#F7F6F1]",
  "landing-nav-links": "hidden items-center gap-8 text-[12px] font-semibold text-[#969890] md:flex [&_a]:transition-colors [&_a]:hover:text-[#F7F6F1]",
  "landing-nav-actions": "flex items-center gap-2",
  "landing-login": "hidden px-3 py-2 text-[12px] font-semibold text-[#A5A59D] transition-colors hover:text-[#F7F6F1] sm:inline-flex",
  "landing-nav-cta": "inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-[#F7F6F1] px-4 text-[11px] font-extrabold text-[#141512] shadow-[0_10px_26px_rgba(0,0,0,0.16)] transition hover:bg-white hover:shadow-[0_14px_32px_rgba(0,0,0,0.2)]",
  "landing-hero": "border-b border-white/10 bg-[#141512] pt-[106px]",
  "landing-hero-inner": "mx-auto grid min-h-[690px] w-[min(1160px,calc(100%-32px))] grid-cols-[minmax(0,0.92fr)_minmax(0,1.08fr)] items-center gap-12 pb-16 lg:gap-16 max-[900px]:grid-cols-1 max-[900px]:gap-8 max-[900px]:pb-10",
  "landing-hero-copy": "relative z-10 max-w-[650px] [&_h1]:m-0 [&_h1]:mt-4 [&_h1]:max-w-[680px] [&_h1]:text-[clamp(48px,6.2vw,84px)] [&_h1]:font-extrabold [&_h1]:leading-[0.95] [&_h1]:tracking-[-0.045em] [&_h1]:text-[#F7F6F1] [&_h1_em]:not-italic [&_h1_em]:text-[#C8F76A] [&_p]:mt-6 [&_p]:max-w-[560px] [&_p]:text-[15px] [&_p]:leading-7 [&_p]:text-[#A2A29A] max-[900px]:max-w-none max-[900px]:[&_h1]:max-w-[720px]",
  "landing-eyebrow": "inline-flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[0.14em] text-[#AAA9A1]",
  "landing-eyebrow-pulse": "h-1.5 w-1.5 rounded-full bg-[#C8F76A] shadow-[0_0_0_6px_rgba(200,247,106,0.09)]",
  "landing-hero-actions": "mt-7 flex flex-wrap gap-2.5",
  "landing-button": "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 text-[11px] font-extrabold transition duration-150 hover:-translate-y-0.5",
  "landing-button-dark": "bg-[#F7F6F1] text-[#141512] shadow-[0_12px_28px_rgba(0,0,0,0.18)] hover:bg-white",
  "landing-button-light": "border border-white/12 bg-white/5 text-[#F7F6F1] hover:bg-white/8",
  "landing-button-lime": "bg-[#C8F76A] text-[#141512] shadow-[0_12px_26px_rgba(200,247,106,0.16)] hover:bg-[#D3FA86]",
  "landing-hero-note": "mt-4 flex flex-wrap items-center gap-x-2.5 gap-y-1 text-[10px] text-[#85867E]",
  "landing-hero-note__dot": "h-1 w-1 rounded-full bg-[#5A5B55]",
  "landing-hero-visual": "relative min-h-[545px] grid place-items-center max-[900px]:min-h-[480px]",
  "landing-product-scene": "relative w-full max-w-[640px] px-2 pb-3",
  "landing-scene-glow": "pointer-events-none absolute -inset-10 rounded-[48px] bg-[radial-gradient(circle_at_55%_40%,rgba(200,247,106,0.11),transparent_42%),radial-gradient(circle_at_75%_80%,rgba(255,255,255,0.05),transparent_35%)] blur-2xl",
  "landing-product-frame": "relative overflow-hidden rounded-[28px] border border-white/12 bg-[#EEEDE7] p-2.5 shadow-[0_34px_90px_rgba(0,0,0,0.34)]",
  "landing-product-window": "overflow-hidden rounded-[21px] border border-black/8 bg-[#FAF9F4] text-[#141512] shadow-[0_14px_40px_rgba(20,21,18,0.09)]",
  "landing-window-top": "flex h-11 items-center justify-between border-b border-[#E7E5DD] bg-white px-4",
  "landing-window-brand": "inline-flex items-center gap-2 text-[11px] font-extrabold",
  "landing-window-dots": "flex items-center gap-1.5",
  "landing-window-dots__dot": "h-1.5 w-1.5 rounded-full bg-[#D3D2CA]",
  "landing-window-body": "grid min-h-[430px] grid-cols-[172px_minmax(0,1fr)] max-[620px]:grid-cols-[54px_minmax(0,1fr)]",
  "landing-mini-sidebar": "border-r border-[#E5E3DB] bg-[#F2F1EB] p-3.5 max-[620px]:p-2",
  "landing-side-title": "mb-4 text-[8px] font-extrabold uppercase tracking-[0.12em] text-[#999A92] max-[620px]:hidden",
  "landing-side-nav": "grid gap-1.5",
  "landing-side-item": "flex items-center gap-2 rounded-xl px-2.5 py-2 text-[10px] font-semibold text-[#7A7B73] max-[620px]:justify-center max-[620px]:px-0",
  "landing-side-item__dot": "h-2 w-2 rounded-[3px] bg-[#D6D4CC]",
  "landing-side-item--active": "bg-white text-[#141512] shadow-[0_5px_15px_rgba(20,21,18,0.05)] [&_.landing-side-item__dot]:bg-[#C8F76A]",
  "landing-mini-main": "min-w-0 p-6 max-[620px]:p-4",
  "landing-mini-header": "flex items-start justify-between gap-4 [&_h3]:m-0 [&_h3]:mt-1 [&_h3]:text-[23px] [&_h3]:font-extrabold [&_h3]:tracking-[-0.025em]",
  "landing-mini-kicker": "text-[8px] font-extrabold uppercase tracking-[0.11em] text-[#999A92]",
  "landing-mini-avatar": "grid h-9 w-9 place-items-center rounded-full bg-[#141512] text-[10px] font-extrabold text-white",
  "landing-mini-search": "mt-5 flex items-center gap-2 rounded-xl border border-[#E5E3DB] bg-white px-3 py-2.5 text-[10px] text-[#999A92] [&_svg]:shrink-0 [&_kbd]:ml-auto [&_kbd]:rounded-md [&_kbd]:bg-[#F2F1EB] [&_kbd]:px-1.5 [&_kbd]:py-1 [&_kbd]:text-[8px]",
  "landing-memory-alert": "mt-4 flex items-center gap-3 rounded-2xl border border-[#DCEACD] bg-[#F0F8E9] p-3",
  "landing-memory-alert-icon": "grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-white text-[#141512] shadow-[0_8px_20px_rgba(40,60,20,0.06)]",
  "landing-memory-alert-copy": "min-w-0 [&_span]:block [&_span]:text-[8px] [&_span]:font-extrabold [&_span]:uppercase [&_span]:tracking-[0.08em] [&_span]:text-[#6C7464] [&_strong]:mt-0.5 [&_strong]:block [&_strong]:truncate [&_strong]:text-[11px] [&_small]:mt-0.5 [&_small]:block [&_small]:text-[9px] [&_small]:text-[#65715D]",
  "landing-mini-section-head": "mt-6 flex items-center justify-between text-[9px] font-extrabold text-[#73746C]",
  "landing-mini-purchases": "mt-2 divide-y divide-[#E7E5DD] rounded-2xl border border-[#E7E5DD] bg-white",
  "landing-mini-purchase": "grid min-h-[66px] grid-cols-[34px_minmax(0,1fr)_auto] items-center gap-3 px-3.5 max-[620px]:grid-cols-[30px_minmax(0,1fr)]",
  "landing-purchase-art": "grid h-8 w-8 place-items-center rounded-lg bg-[#E7E2D2] text-[9px] font-extrabold",
  "landing-purchase-copy": "min-w-0 [&_strong]:block [&_strong]:truncate [&_strong]:text-[10px] [&_strong]:font-bold [&_span]:mt-0.5 [&_span]:block [&_span]:truncate [&_span]:text-[9px] [&_span]:text-[#85867E]",
  "landing-purchase-tag": "rounded-full border border-[#E5E3DB] bg-[#FAF9F4] px-2 py-1 text-[8px] font-bold text-[#77786F] max-[620px]:hidden",
  "landing-float-card": "absolute z-20 flex items-center gap-2.5 rounded-2xl border border-black/6 bg-white/96 p-2.5 text-[#141512] shadow-[0_18px_44px_rgba(0,0,0,0.16)] backdrop-blur-[8px]",
  "landing-float-proof": "bottom-5 left-[-10px] max-[620px]:left-0",
  "landing-float-reminder": "right-[-8px] top-6 max-[620px]:right-0",
  "landing-float-icon": "grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#F2F1EB]",
  "landing-float-copy": "grid gap-0.5 [&_strong]:text-[10px] [&_small]:text-[9px] [&_small]:text-[#77786F]",
  "landing-trust-row": "mt-7 grid max-w-[560px] grid-cols-3 border-t border-white/10 pt-4 max-[520px]:grid-cols-1 max-[520px]:gap-2.5",
  "landing-trust-item": "flex items-center gap-2 text-[9px] font-semibold text-[#8B8C84]",
  "landing-trust-dot": "h-1.5 w-1.5 rounded-full bg-[#C8F76A]",
  "landing-principles": "bg-[#F7F6F1] py-24 text-[#141512] max-[760px]:py-20",
  "landing-principles-grid": "grid grid-cols-[1.05fr_0.65fr_0.65fr] gap-4 max-[900px]:grid-cols-1",
  "landing-principles-intro": "pr-12 max-[900px]:pr-0 [&_h2]:m-0 [&_h2]:mt-3 [&_h2]:max-w-[570px] [&_h2]:text-[clamp(40px,5vw,68px)] [&_h2]:font-extrabold [&_h2]:leading-[0.98] [&_h2]:tracking-[-0.045em] [&_p]:mt-4 [&_p]:max-w-[460px] [&_p]:text-[13px] [&_p]:leading-6 [&_p]:text-[#77786F]",
  "landing-section-label": "text-[9px] font-extrabold uppercase tracking-[0.14em] text-[#85867E]",
  "landing-principle-card": "rounded-3xl border border-[#E1DFD7] bg-white p-6 shadow-[0_12px_30px_rgba(20,21,18,0.035)] [&_.landing-principle-icon]:mb-12 [&_h3]:m-0 [&_h3]:text-[14px] [&_h3]:font-extrabold [&_p]:mt-2 [&_p]:text-[11px] [&_p]:leading-5 [&_p]:text-[#77786F]",
  "landing-principle-icon": "grid h-10 w-10 place-items-center rounded-xl bg-[#EFF7E7] text-[#141512]",
  "landing-how": "border-y border-white/10 bg-[#141512] py-24 max-[760px]:py-20",
  "landing-how-heading": "max-w-[650px] [&_h2]:m-0 [&_h2]:mt-3 [&_h2]:text-[clamp(40px,5vw,66px)] [&_h2]:font-extrabold [&_h2]:leading-[0.98] [&_h2]:tracking-[-0.045em]",
  "landing-how-grid": "mt-14 grid grid-cols-3 divide-x divide-white/10 max-[760px]:grid-cols-1 max-[760px]:divide-x-0 max-[760px]:divide-y",
  "landing-how-step": "px-8 first:pl-0 last:pr-0 max-[760px]:px-0 max-[760px]:py-6",
  "landing-how-number": "text-[10px] font-extrabold tracking-[0.1em] text-[#6F716A]",
  "landing-how-icon": "mt-7 grid h-10 w-10 place-items-center rounded-xl bg-white/8 text-[#C8F76A]",
  "landing-how-step-h3": "",
  "landing-how-step-copy": "mt-5 [&_h3]:m-0 [&_h3]:text-[17px] [&_h3]:font-extrabold [&_p]:mt-2 [&_p]:max-w-[260px] [&_p]:text-[11px] [&_p]:leading-5 [&_p]:text-[#999A92]",
  "landing-cta": "bg-[#F7F6F1] py-24 text-[#141512] max-[760px]:py-20",
  "landing-cta-card": "relative overflow-hidden rounded-[30px] bg-[#141512] p-10 text-[#F7F6F1] shadow-[0_26px_60px_rgba(20,21,18,0.12)] md:p-14 [&>div]:relative [&>div]:z-10 [&_h2]:m-0 [&_h2]:mt-3 [&_h2]:max-w-[720px] [&_h2]:text-[clamp(40px,5.5vw,74px)] [&_h2]:font-extrabold [&_h2]:leading-[0.97] [&_h2]:tracking-[-0.045em] [&_p]:mt-4 [&_p]:max-w-[560px] [&_p]:text-[13px] [&_p]:leading-6 [&_p]:text-[#A0A19A]",
  "landing-cta-glow": "pointer-events-none absolute -right-20 -top-20 h-72 w-72 rounded-full bg-[#C8F76A]/12 blur-3xl",
  "landing-footer": "border-t border-[#DAD8D0] bg-[#EEEDE7] text-[#141512]",
  "landing-footer-top": "flex items-start justify-between gap-12 py-12 max-[760px]:flex-col max-[760px]:gap-8",
  "landing-footer-brand": "max-w-[420px] [&_p]:mt-3 [&_p]:text-[11px] [&_p]:leading-6 [&_p]:text-[#6F716A]",
  "landing-footer-links": "grid grid-cols-2 gap-x-10 gap-y-3 pt-1 [&_a]:text-[11px] [&_a]:font-bold [&_a]:text-[#5F6059] [&_a]:transition-colors [&_a]:hover:text-[#141512]",
  "landing-footer-bottom": "flex min-h-[58px] items-center justify-between gap-5 border-t border-[#DAD8D0] text-[9px] text-[#7B7C74] max-[760px]:flex-col max-[760px]:items-start max-[760px]:justify-center max-[760px]:gap-1.5 max-[760px]:py-4",
  "landing-footer-meta": "flex flex-wrap items-center gap-2",
  "landing-footer-meta-dot": "h-1 w-1 rounded-full bg-[#A7A8A0]",
  "landing-mobile-nav": "hidden",
  "landing-language-option": "",

};

export function tw(value: string): string {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((token) => styles[token] ?? "")
    .filter(Boolean)
    .join(" ");
}
