type StyleValue = string;

const styles: Record<string, StyleValue> = {
  /* shared */
  "button": "inline-flex min-h-[42px] items-center justify-center gap-2 rounded-xl border border-transparent px-4 text-[12px] font-bold tracking-[-0.01em] transition duration-150 ease-out hover:-translate-y-0.5 disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-55",
  "button-dark": "border-[#171713] bg-[#171713] text-white shadow-[0_12px_26px_rgba(23,23,19,0.14)] hover:bg-[#2b2b26] hover:shadow-[0_14px_30px_rgba(23,23,19,0.18)]",
  "button-light": "border-[#dfded7] bg-white/80 text-[#171713] shadow-[0_4px_14px_rgba(24,24,20,0.04)] hover:border-[#c9c8c0] hover:bg-white",
  "button-lime": "border-[#b8ff77] bg-[#b8ff77] text-[#171713] shadow-[0_12px_28px_rgba(184,255,119,0.18)]",
  "button-danger": "border-[#ead8d8] bg-[#faf1f1] text-[#8d5656] hover:border-[#dfc3c3] hover:bg-[#f8eaea]",
  "app-kicker": "block text-[9px] font-extrabold uppercase tracking-[0.1em] text-[#8b8c84]",
  "panel-kicker": "block text-[9px] font-extrabold uppercase tracking-[0.1em] text-[#8b8c84]",
  "language-toggle": "inline-flex min-h-[38px] min-w-[78px] items-center justify-center gap-0.5 rounded-full border border-[#d7d7cf] bg-white/90 p-[3px] text-[10px] font-bold leading-none text-[#171713] shadow-[0_5px_16px_rgba(24,24,20,0.05)] transition hover:border-[#bdbdb5] hover:bg-white hover:shadow-[0_7px_20px_rgba(24,24,20,0.08)] focus-visible:outline-2 focus-visible:outline-[#8be84d] focus-visible:outline-offset-2 [&_span]:grid [&_span]:h-[30px] [&_span]:min-w-[33px] [&_span]:place-items-center [&_span]:rounded-full [&_span]:px-1.5 [&_span]:text-[#77786f] [&_span]:whitespace-nowrap [&_span]:transition-colors",
  "is-active": "bg-[#171713] !text-white",
  "brand-logo": "inline-flex items-center gap-2.5 font-extrabold tracking-[-0.05em] text-[#171713]",
  "brand-logo--sm": "text-base",
  "brand-logo--md": "text-xl",
  "brand-logo--lg": "text-2xl",
  "brand-logo--inverted": "text-[#f7f6f2]",
  "brand-logo__mark": "inline-flex h-7 w-7 shrink-0 items-center justify-center gap-[3px] rounded-[9px] bg-[#171713] p-1.5",
  "brand-logo__name": "leading-none",
  "auth-shell": "flex min-h-screen w-full flex-col overflow-x-hidden bg-[radial-gradient(circle_at_12%_8%,rgba(184,255,119,0.16),transparent_24rem),radial-gradient(circle_at_88%_18%,rgba(219,232,255,0.24),transparent_28rem),#f7f6f2] px-5 pb-[22px] pt-[18px]",
  "auth-topbar": "mx-auto flex min-h-[42px] w-full max-w-[1180px] items-center justify-between gap-5",
  "auth-content": "mx-auto flex w-full max-w-[1180px] flex-1 items-start justify-center px-0 pb-[18px] pt-[clamp(22px,4vh,48px)]",
  "auth-card": "w-[min(100%,620px)] rounded-[32px] border border-black/[0.07] bg-white/90 p-[clamp(28px,4vw,46px)] shadow-[0_22px_65px_rgba(26,25,20,0.1)] backdrop-blur [&>h1]:m-0 [&>h1]:max-w-[570px] [&>h1]:text-[clamp(44px,6.2vw,64px)] [&>h1]:leading-[0.99] [&>h1]:tracking-[-0.065em] [&>h1]:text-[#171713] [&>p]:mt-[17px] [&>p]:max-w-[560px] [&>p]:text-[clamp(15px,2vw,17px)] [&>p]:leading-[1.58] [&>p]:text-[#6f7068]",
  "auth-eyebrow": "mb-4 inline-flex items-center text-[9px] font-extrabold uppercase tracking-[0.11em] text-[#77786f]",
  "auth-footer": "mt-4 text-center text-[10px] text-[#96978f]",
  "auth-form": "mt-7 flex flex-col gap-4 [&_label]:grid [&_label]:gap-2 [&_label>span]:text-[13px] [&_label>span]:font-bold [&_input]:min-h-[58px] [&_input]:rounded-2xl [&_input]:border [&_input]:border-[#d9d7cf] [&_input]:bg-white [&_input]:px-[17px] [&_input]:text-base [&_input]:text-[#171713] [&_input]:outline-none [&_input]:transition [&_input]:placeholder:text-[#9a9b93] [&_input]:focus:border-[#a9aaa3] [&_input]:focus:ring-4 [&_input]:focus:ring-[#c8f77a22]",
  "auth-primary-social": "w-full",
  "auth-google-button": "grid min-h-[62px] w-full grid-cols-[42px_minmax(0,1fr)_42px] items-center gap-2 rounded-2xl border border-[#d9d7cf] bg-white px-3.5 text-[#171713] shadow-[0_10px_28px_rgba(23,23,19,0.05)] transition hover:-translate-y-px hover:border-[#bbb9b0] hover:shadow-[0_14px_34px_rgba(23,23,19,0.08)] focus-visible:outline-2 focus-visible:outline-[#8be84d] focus-visible:outline-offset-2 disabled:cursor-wait disabled:opacity-55 disabled:hover:translate-y-0",
  "auth-google-button__icon": "grid h-9 w-9 place-items-center justify-self-start rounded-[11px] border border-[#e2e0d8] bg-[#fafaf7]",
  "auth-google-button__copy": "flex min-w-0 flex-col items-center justify-center gap-0.5 text-center [&_strong]:text-[14px] [&_strong]:font-extrabold [&_strong]:leading-[1.25] [&_small]:text-[11px] [&_small]:leading-[1.35] [&_small]:text-[#878880]",
  "auth-google-button__arrow": "justify-self-end text-xl leading-none text-[#777870] transition-transform group-hover:translate-x-0.5",
  "auth-divider": "my-0.5 flex items-center gap-3.5 text-[11px] text-[#96978f] before:h-px before:flex-1 before:bg-[#e4e3dc] after:h-px after:flex-1 after:bg-[#e4e3dc]",
  "auth-fields": "flex flex-col gap-4",
  "auth-message": "rounded-xl px-3 py-2.5 text-[11px] leading-relaxed",
  "auth-message--error": "border border-[#ead8d8] bg-[#faf1f1] text-[#7d4d4d]",
  "auth-message--success": "border border-[#d6e6c8] bg-[#eef7e9] text-[#4e6b3c] [&_p]:mt-1.5",
  "auth-submit": "min-h-[58px] rounded-2xl text-[15px]",
  "auth-link": "text-[12px] font-semibold text-[#6f7068] underline-offset-4 hover:text-[#171713] hover:underline",
  "auth-link--center": "mt-[-1px] text-center",
  "auth-switch": "mt-px text-center text-[12px] text-[#77786f] [&_a]:font-bold [&_a]:text-[#171713] [&_a]:hover:underline",
  "app-shell": "flex min-h-screen bg-[#f7f6f2]",
  "app-sidebar": "sticky top-0 flex h-screen w-[230px] shrink-0 flex-col border-r border-[#dfded7] bg-white/88 px-[18px] py-5 backdrop-blur",
  "app-sidebar__brand": "mb-5 inline-flex px-1 py-1",
  "app-sidebar__workspace": "mb-4 rounded-xl bg-[#f4f4ef] px-3 py-2.5 [&_span]:text-[9px] [&_span]:font-extrabold [&_span]:uppercase [&_span]:tracking-[0.1em] [&_span]:text-[#8b8c84]",
  "app-sidebar__bottom": "mt-auto space-y-3",
  "user-chip": "flex min-w-0 items-center gap-2 rounded-xl border border-[#e6e5de] bg-[#fafaf7] px-2.5 py-2",
  "user-chip__avatar": "grid h-8 w-8 shrink-0 place-items-center rounded-[10px] bg-[#171713] text-xs font-extrabold text-white",
  "user-chip__email": "min-w-0 truncate text-[10px] text-[#6f7068]",
  "signout-button": "inline-flex min-h-9 w-full items-center justify-center gap-2 rounded-xl border border-transparent bg-transparent px-2 text-[11px] font-semibold text-[#6f7068] transition hover:border-[#dfded7] hover:bg-[#f5f5f1] hover:text-[#171713] disabled:cursor-wait disabled:opacity-50",
  "app-main": "min-w-0 flex-1",
  "app-topbar": "sticky top-0 z-40 flex min-h-[68px] items-center justify-between gap-4 border-b border-[#dfded7] bg-[#f7f6f2]/90 px-8 backdrop-blur",
  "app-content": "mx-auto w-full max-w-[1180px] px-8 py-7 md:px-8",
  "app-nav": "flex flex-col gap-1 [&_.app-nav__item]:flex [&_.app-nav__item]:items-center [&_.app-nav__item]:gap-2.5 [&_.app-nav__item]:rounded-xl [&_.app-nav__item]:px-3 [&_.app-nav__item]:py-2.5 [&_.app-nav__item]:text-[11px] [&_.app-nav__item]:font-bold [&_.app-nav__item]:text-[#86877f] [&_.app-nav__item]:transition [&_.app-nav__item]:hover:bg-[#f5f5f1] [&_.app-nav__item]:hover:text-[#171713] [&_.app-nav__item].active:bg-[#171713] [&_.app-nav__item].active:text-white",
  "app-nav--mobile": "fixed inset-x-3 bottom-3 z-50 grid grid-cols-4 gap-1 rounded-2xl border border-[#dfded7] bg-white/95 p-1.5 shadow-[0_18px_40px_rgba(23,23,19,0.14)] backdrop-blur md:hidden",
  "app-nav__item": "relative justify-center",
  "active": "",
  "app-header": "mb-6 flex items-start justify-between gap-5 [&_h1]:m-0 [&_h1]:text-[clamp(30px,4vw,42px)] [&_h1]:font-extrabold [&_h1]:tracking-[-0.05em] [&_p]:m-0",
  "dashboard-header": "",
  "dashboard-header__subtitle": "mt-2 max-w-[650px] text-[13px] leading-7 text-[#77786f]",
  "app-header__actions": "flex shrink-0 items-center gap-2",
  "app-add-button": "min-h-10 rounded-xl",
  "page-back-link": "mb-2 inline-flex items-center text-[11px] font-semibold text-[#85867e] transition hover:text-[#171713]",
  "app-page-header": "mb-6 flex items-end justify-between gap-5 [&>div:first-child]:min-w-0 [&_h1]:m-0 [&_h1]:mt-1.5 [&_h1]:text-[clamp(30px,4vw,40px)] [&_h1]:font-extrabold [&_h1]:tracking-[-0.05em] [&_p]:mt-2 [&_p]:text-[12px] [&_p]:leading-relaxed [&_p]:text-[#7c7d74]",
  "app-page-header__action": "shrink-0",
  "command-trigger": "inline-flex min-h-10 min-w-[250px] items-center justify-between gap-3 rounded-xl border border-[#dfded7] bg-white/80 px-3 text-[11px] text-[#8a8b82] shadow-[0_3px_12px_rgba(24,24,20,0.03)] hover:border-[#c9c8c0] hover:bg-white focus-visible:outline-2 focus-visible:outline-[#8be84d] focus-visible:outline-offset-2 [&_kbd]:rounded-md [&_kbd]:bg-[#f1f1ed] [&_kbd]:px-1.5 [&_kbd]:py-1 [&_kbd]:text-[9px]",
  "command-trigger__search": "inline-flex min-w-0 items-center gap-2 truncate",
  "command-overlay": "fixed inset-0 z-[100] grid place-items-start bg-black/30 px-4 pt-[14vh] backdrop-blur-[2px]",
  "command-dialog": "w-full max-w-[620px] overflow-hidden rounded-2xl border border-[#dfded7] bg-white shadow-[0_30px_80px_rgba(23,23,19,0.2)]",
  "command-input-wrap": "flex min-h-14 items-center gap-3 border-b border-[#e6e5de] px-4 [&_input]:min-w-0 [&_input]:flex-1 [&_input]:border-0 [&_input]:bg-transparent [&_input]:text-sm [&_input]:outline-none [&_input]:ring-0 [&_input]:placeholder:text-[#a0a19a] [&_kbd]:text-[9px] [&_kbd]:text-[#8a8b82]",
  "command-list": "max-h-[360px] overflow-y-auto p-1.5",
  "command-item": "flex w-full items-center gap-3 rounded-xl border-0 bg-transparent px-3 py-2.5 text-left transition hover:bg-[#f4f4ef] focus-visible:bg-[#f4f4ef] [&.selected]:bg-[#eef5e8]",
  "command-item__icon": "grid h-8 w-8 shrink-0 place-items-center rounded-[9px] bg-[#f4f4ef] text-[#6f7068]",
  "command-item__label": "min-w-0 flex-1 truncate text-[12px] font-semibold text-[#171713]",
  "command-empty": "m-0 px-3 py-10 text-center text-[12px] text-[#8a8b82]",
  "command-footer": "flex flex-wrap gap-4 border-t border-[#e6e5de] px-4 py-2.5 text-[9px] text-[#8a8b82] [&_kbd]:rounded bg-[#f4f4ef] [&_kbd]:px-1",
  "loading-skeleton": "animate-pulse rounded-xl bg-[#e7e6df]",
  "loading-skeleton--title": "h-8 w-2/5",
  "loading-skeleton--line": "mt-3 h-4 w-1/2",
  "loading-skeleton--panel": "mt-6 h-44 w-full",
  "loading-skeleton-list": "mt-3 space-y-2",
  "loading-skeleton--row": "h-16 w-full",
  /* dashboard */
  "attention-panel": "rounded-2xl border border-[#dfded7] bg-white p-5 shadow-[0_10px_28px_rgba(23,23,19,0.04)]",
  "dashboard-hero": "relative mb-5 grid min-h-[245px] grid-cols-[minmax(0,1fr)_160px] overflow-hidden rounded-[22px] bg-[#171713] p-7 text-[#f7f6f2] shadow-[0_20px_55px_rgba(23,23,19,0.12)]",
  "dashboard-hero--empty": "min-h-[220px]",
  "dashboard-hero__grain": "pointer-events-none absolute inset-0 opacity-60 [background-image:radial-gradient(circle_at_20%_20%,rgba(184,255,119,0.1),transparent_25rem),radial-gradient(circle_at_90%_70%,rgba(219,232,255,0.08),transparent_22rem)]",
  "dashboard-hero__copy": "relative z-10 self-center [&_h2]:m-0 [&_h2]:max-w-[620px] [&_h2]:text-[clamp(32px,4vw,54px)] [&_h2]:font-extrabold [&_h2]:tracking-[-0.06em] [&_p]:mt-3 [&_p]:max-w-[560px] [&_p]:text-[13px] [&_p]:leading-7 [&_p]:text-[#b8b8af]",
  "dashboard-hero__meta": "mt-3 flex flex-wrap items-center gap-2 text-[10px] text-[#b1b1a8]",
  "dashboard-hero__amount": "mt-5 block text-[26px] font-extrabold tracking-[-0.04em]",
  "dashboard-hero__link": "mt-5 inline-flex items-center gap-2 text-[11px] font-bold text-[#b8ff77] hover:underline",
  "dashboard-hero__mark": "relative z-10 ml-auto grid h-[145px] w-[145px] place-self-center place-items-center rounded-[38px] bg-white/[0.05] [&_span]:block [&_span]:h-12 [&_span]:w-2.5 [&_span]:rounded-full [&_span:nth-child(1)]:bg-[#6e755e] [&_span:nth-child(2)]:h-16 [&_span:nth-child(2)]:bg-[#95a47c] [&_span:nth-child(3)]:h-20 [&_span:nth-child(3)]:bg-[#b8ff77]",
  "recent-panel": "overflow-hidden rounded-2xl border border-[#dfded7] bg-white",
  "recent-panel__heading": "flex min-h-[72px] items-center justify-between gap-4 border-b border-[#e6e5de] px-5 py-3.5 [&>div]:min-w-0 [&_h2]:m-0 [&_h2]:mt-1 [&_h2]:text-[17px] [&_h2]:font-extrabold [&_h2]:tracking-[-0.035em]",
  "dashboard-purchase-list": "divide-y divide-[#e8e7e1]",
  "dashboard-purchase-row": "grid min-h-[72px] grid-cols-[36px_minmax(0,1fr)_auto_auto] items-center gap-3 px-5 py-3.5 transition hover:bg-[#fafaf7] [&>.purchase-meta]:min-w-0",
  "dashboard-purchase-amount": "text-[12px] font-bold text-[#171713]",
  "dashboard-row-chevron": "text-[#8a8b82] transition group-hover:translate-x-0.5",
  "dashboard-inline-note": "flex items-center justify-between gap-4 border-t border-[#e6e5de] px-5 py-4 text-[11px] text-[#77786f] [&_a]:font-bold [&_a]:text-[#171713]",
  /* purchase base */
  "purchases-section": "space-y-4",
  "purchase-search": "grid grid-cols-[minmax(0,1fr)_auto_auto] gap-2.5 rounded-2xl border border-[#dfded7] bg-white p-4 shadow-[0_8px_22px_rgba(23,23,19,0.035)]",
  "purchase-search__filters": "col-span-full grid grid-cols-5 gap-2.5",
  "purchase-search__checks": "col-span-full flex flex-wrap gap-4 border-t border-[#e6e5de] pt-3 text-[10px] text-[#6f7068] [&_label]:inline-flex [&_label]:items-center [&_label]:gap-1.5",
  "purchase-results": "overflow-hidden rounded-2xl border border-[#dfded7] bg-white",
  "purchase-result": "group grid min-h-[72px] grid-cols-[38px_minmax(0,1fr)_auto_auto] items-center gap-3 border-b border-[#e8e7e1] px-4 py-3.5 last:border-b-0 hover:bg-[#fafaf7]",
  "purchase-result__icon": "grid h-10 w-10 place-items-center rounded-xl bg-[#dbe8ff] text-[12px] font-extrabold text-[#2e3027]",
  "purchase-result__icon--large": "h-[52px] w-[52px] rounded-2xl text-[16px]",
  "purchase-result__body": "min-w-0 [&_strong]:block [&_strong]:truncate [&_strong]:text-[12px] [&_strong]:font-bold [&_span]:mt-1 [&_span]:block [&_span]:truncate [&_span]:text-[10px] [&_span]:text-[#85867e]",
  "purchase-result__amount": "text-[12px] font-extrabold text-[#171713]",
  "purchase-result__chevron": "text-[#8a8b82] transition group-hover:translate-x-0.5",
  "purchase-empty": "grid min-h-[320px] place-items-center content-center gap-2 rounded-2xl border border-[#dfded7] bg-white p-8 text-center [&_h2]:m-0 [&_h2]:text-xl [&_h2]:font-extrabold [&_p]:m-0 [&_p]:max-w-[420px] [&_p]:text-[12px] [&_p]:leading-6 [&_p]:text-[#77786f]",
  "empty-icon": "grid h-10 w-10 place-items-center rounded-xl bg-[#f3f3ee] text-lg text-[#8a8b82]",
  "purchase-editor": "mx-auto w-full max-w-[760px]",
  "purchase-form": "grid gap-4 rounded-[22px] border border-[#dfded7] bg-white p-6 shadow-[0_14px_35px_rgba(23,23,19,0.06)] [&>label]:min-w-0 [&>label]:space-y-1.5 [&>label>span]:block [&>label>span]:text-[11px] [&>label>span]:font-bold [&_input:not([type=checkbox])]:min-h-11 [&_input:not([type=checkbox])]:w-full [&_input:not([type=checkbox])]:rounded-lg [&_input:not([type=checkbox])]:border [&_input:not([type=checkbox])]:border-[#d4d3cc] [&_input:not([type=checkbox])]:bg-white [&_input:not([type=checkbox])]:px-3 [&_input:not([type=checkbox])]:text-[12px] [&_input:not([type=checkbox])]:text-[#171713] [&_input:not([type=checkbox])]:outline-none [&_input:not([type=checkbox])]:focus:border-[#a9aaa3] [&_input:not([type=checkbox])]:focus:ring-4 [&_input:not([type=checkbox])]:focus:ring-[#c8f77a22] [&_textarea]:min-h-[110px] [&_textarea]:w-full [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-[#d4d3cc] [&_textarea]:bg-white [&_textarea]:p-3 [&_textarea]:text-[12px] [&_textarea]:outline-none [&_textarea]:focus:border-[#a9aaa3] [&_textarea]:focus:ring-4 [&_textarea]:focus:ring-[#c8f77a22] [&_em]:not-italic [&_em]:font-normal [&_em]:text-[#8a8b82]",
  "purchase-form-grid": "grid grid-cols-2 gap-2.5 max-[720px]:grid-cols-1",
  "money-input": "flex items-center overflow-hidden rounded-lg border border-[#d4d3cc] bg-white focus-within:border-[#a9aaa3] focus-within:ring-4 focus-within:ring-[#c8f77a22] [&>span]:px-3 [&>span]:text-[#8a8b82] [&_input]:border-0 [&_input]:focus:ring-0",
  "field-error": "block text-[9px] text-[#8f5959]",
  "field-hint": "block text-[9px] leading-5 text-[#8a8b82]",
  "purchase-form-proof-note": "grid gap-1 rounded-xl border border-[#dce7d3] bg-[#f1f8eb] p-3 [&_strong]:text-[11px] [&_span]:text-[10px] [&_span]:text-[#6f7b66]",
  "purchase-submit": "min-h-11",
  "purchase-editor-cancel": "mt-3 inline-flex text-[11px] font-semibold text-[#77786f] hover:text-[#171713] hover:underline",
  "purchase-detail": "overflow-hidden rounded-2xl border border-[#dfded7] bg-white",
  "purchase-detail__hero": "flex items-center gap-4 border-b border-[#e6e5de] px-6 py-5 [&_h2]:m-1.5 [&_h2]:text-2xl [&_h2]:font-extrabold [&_h2]:tracking-[-0.04em] [&_strong]:block [&_strong]:mt-1 [&_strong]:text-xl [&_strong]:font-extrabold",
  "purchase-detail__grid": "grid grid-cols-4 divide-x divide-[#e6e5de] max-[820px]:grid-cols-2 max-[520px]:grid-cols-1",
  "detail-cell": "min-w-0 p-5 [&_span]:block [&_span]:text-[9px] [&_span]:font-bold [&_span]:uppercase [&_span]:tracking-[0.08em] [&_span]:text-[#8a8b82] [&_strong]:mt-2 [&_strong]:block [&_strong]:truncate [&_strong]:text-[12px]",
  "purchase-detail__section": "border-t border-[#e6e5de] p-6 [&>small]:block [&>small]:mt-2 [&>small]:text-[9px] [&>small]:text-[#8a8b82]",
  "purchase-note": "mt-2 whitespace-pre-wrap text-[12px] leading-6 text-[#4e4f48]",
  "purchase-note--empty": "text-[#9a9b93]",
  "purchase-detail__actions": "flex flex-wrap justify-end gap-2.5 pt-4",
  "purchase-documents": "mt-5 rounded-2xl border border-[#dfded7] bg-white p-5",
  "purchase-documents__header": "mb-4 [&_p]:mt-1.5 [&_p]:max-w-[640px] [&_p]:text-[11px] [&_p]:leading-6 [&_p]:text-[#77786f]",
  "purchase-documents__uploader": "rounded-xl border border-dashed border-[#cfcfc7] bg-[#fafaf7] p-4",
  "purchase-documents__controls": "grid grid-cols-2 gap-3 max-[720px]:grid-cols-1 [&_label]:grid [&_label]:gap-1.5 [&_label>span]:text-[10px] [&_label>span]:font-bold",
  "purchase-documents__upload-row": "mt-3 flex items-center justify-between gap-3 rounded-lg bg-white px-3 py-2.5 text-[10px] text-[#77786f]",
  "document-status": "mt-3 rounded-lg border border-[#d6e6c8] bg-[#eef7e9] px-3 py-2 text-[10px] text-[#4e6b3c]",
  "document-error": "mt-3 rounded-lg border border-[#ead8d8] bg-[#faf1f1] px-3 py-2 text-[10px] text-[#7d4d4d]",
  "purchase-document-list": "mt-4 divide-y divide-[#e6e5de] rounded-xl border border-[#e6e5de] bg-white",
  "purchase-document-row": "grid grid-cols-[40px_minmax(0,1fr)_auto] items-center gap-3 px-3.5 py-3",
  "purchase-document-row__icon": "grid h-9 w-9 place-items-center rounded-lg bg-[#f3f3ee] text-[8px] font-extrabold text-[#77786f]",
  "purchase-document-row__body": "min-w-0 [&_strong]:block [&_strong]:truncate [&_strong]:text-[11px] [&_span]:mt-1 [&_span]:block [&_span]:text-[9px] [&_span]:text-[#8a8b82]",
  "purchase-document-row__actions": "flex items-center gap-1.5",
  "purchase-documents__empty": "m-0 mt-4 rounded-xl bg-[#fafaf7] px-4 py-8 text-center text-[10px] text-[#8a8b82]",
  /* extras */
  "purchase-extras": "mt-5 space-y-4 rounded-2xl border border-[#dfded7] bg-white p-5",
  "purchase-extras__block": "rounded-xl border border-[#e6e5de] p-4 [&>h3]:m-0 [&>h3]:mb-3 [&>h3]:text-[12px] [&>h3]:font-extrabold [&>p]:m-0 [&>p]:text-[11px] [&>p]:leading-6 [&>p]:text-[#77786f]",
  "purchase-extra-row": "flex items-center justify-between gap-3 border-t border-[#ecebe5] py-3 first:border-t-0 [&>div:first-child]:min-w-0 [&_strong]:block [&_strong]:truncate [&_strong]:text-[11px] [&_span]:mt-1 [&_span]:block [&_span]:truncate [&_span]:text-[9px] [&_span]:text-[#8a8b82]",
  "purchase-extras__form": "mt-3 grid grid-cols-6 gap-2 max-[900px]:grid-cols-2 max-[520px]:grid-cols-1 [&>*]:min-w-0",
  /* reminders */
  "reminders-layout": "grid grid-cols-[minmax(0,1.08fr)_minmax(320px,0.72fr)] items-start gap-8 max-[900px]:grid-cols-1",
  "reminder-header-count": "inline-flex min-h-8 items-center rounded-full border border-[#dfded7] bg-white px-2.5 text-[10px] font-bold text-[#6f7068]",
  "reminder-page-message": "mb-4 text-[11px] text-[#6f7068]",
  "reminder-list-panel": "overflow-hidden rounded-2xl border border-[#dfded7] bg-white",
  "reminder-list-panel__heading": "flex min-h-[70px] items-center justify-between gap-4 border-b border-[#e6e5de] px-[18px] py-4 [&_h2]:m-1 [&_h2]:text-[18px] [&_h2]:font-extrabold [&_h2]:tracking-[-0.035em]",
  "reminder-count": "grid h-7 min-w-7 place-items-center rounded-lg bg-[#f1f1ed] px-1.5 text-[9px] font-extrabold tabular-nums text-[#6f7068]",
  "reminder-group": "px-[18px] pt-[18px] last:pb-[18px] [&>h3]:m-0 [&>h3]:mb-2 [&>h3]:text-[9px] [&>h3]:font-extrabold [&>h3]:uppercase [&>h3]:tracking-[0.1em] [&>h3]:text-[#9a9b93]",
  "reminder-rows": "border-t border-[#e6e5de]",
  "reminder-row": "grid min-h-[76px] grid-cols-[34px_minmax(0,1fr)_auto] items-center gap-3 border-b border-[#e6e5de] py-3 last:border-b-0",
  "reminder-row--completed": "opacity-55",
  "reminder-row__mark": "grid h-[30px] w-[30px] place-items-center rounded-lg border border-[#dfded7] bg-[#f8f8f5] text-[#6f7068]",
  "reminder-row__body": "min-w-0",
  "reminder-row__title": "flex min-w-0 flex-wrap items-center gap-2 [&_strong]:min-w-0 [&_strong]:truncate [&_strong]:text-[12px] [&_strong]:tracking-[-0.01em]",
  "reminder-type": "inline-flex min-h-[18px] items-center rounded border border-[#dfded7] bg-[#fafaf7] px-1.5 text-[8px] font-bold text-[#8a8b82]",
  "reminder-row__meta": "mt-1 block truncate text-[10px] text-[#6f7068]",
  "reminder-row__due": "mt-0.5 block truncate text-[9px] font-bold text-[#171713]",
  "reminder-row__actions": "inline-flex items-center gap-1",
  "reminder-icon-button": "grid h-[30px] w-[30px] place-items-center rounded-lg border border-transparent bg-transparent text-[#6f7068] hover:border-[#dfded7] hover:bg-[#f3f3f0] hover:text-[#171713] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#d7efbd]",
  "reminder-icon-button--danger": "hover:border-[#ead8d8] hover:bg-[#faf1f1] hover:text-[#8d5656]",
  "reminder-empty": "grid min-h-[280px] place-items-center content-center px-6 py-11 text-center",
  "reminder-empty__icon": "grid h-10 w-10 place-items-center rounded-xl border border-[#dfded7] bg-[#f8f8f5] text-[#6f7068]",
  "reminder-form-panel": "sticky top-[78px] rounded-2xl border border-[#dfded7] bg-white max-[900px]:static",
  "reminder-form-panel__heading": "flex min-h-[70px] items-center justify-between gap-4 border-b border-[#e6e5de] px-[18px] py-4 [&_h2]:m-1 [&_h2]:text-[18px] [&_h2]:font-extrabold]",
  "reminder-form": "grid gap-3.5 p-[18px] [&>label]:mb-0 [&>label]:space-y-1.5 [&_label>span]:block [&_label>span]:text-[10px] [&_label>span]:font-bold [&_input:not([type=checkbox])]:min-h-10 [&_input:not([type=checkbox])]:w-full [&_input:not([type=checkbox])]:rounded-lg [&_input:not([type=checkbox])]:border [&_input:not([type=checkbox])]:border-[#d4d3cc] [&_input:not([type=checkbox])]:bg-white [&_input:not([type=checkbox])]:px-2.5 [&_input:not([type=checkbox])]:text-[11px] [&_input:not([type=checkbox])]:outline-none [&_textarea]:w-full [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-[#d4d3cc] [&_textarea]:bg-white [&_textarea]:p-2.5 [&_textarea]:text-[11px] [&_textarea]:outline-none [&_input:not([type=checkbox])]:focus:border-[#a9aaa3] [&_textarea]:focus:border-[#a9aaa3] [&_input:not([type=checkbox])]:focus:ring-4 [&_textarea]:focus:ring-4 [&_input:not([type=checkbox])]:focus:ring-[#c8f77a22] [&_textarea]:focus:ring-[#c8f77a22]",
  "reminder-form-grid": "grid grid-cols-[0.82fr_1.18fr] gap-2.5 max-[760px]:grid-cols-1",
  "reminder-offsets": "grid grid-cols-3 gap-1.5",
  "reminder-offset": "inline-flex min-h-9 items-center gap-2 rounded-lg border border-[#dfded7] bg-[#fafaf7] px-2 text-[9px] text-[#6f7068] [&:has(input:checked)]:border-[#cadbb8] [&:has(input:checked)]:bg-[#f0f6e8] [&:has(input:checked)]:text-[#171713]",
  "reminder-enabled": "inline-flex items-center gap-2 text-[10px] text-[#6f7068]",
  "reminder-field-error": "block text-[9px] text-[#8f5959]",
  "reminder-message": "mb-1 rounded-lg px-2.5 py-2.5 text-[10px] leading-5",
  "reminder-message--error": "border border-[#ead8d8] bg-[#faf1f1] text-[#7d4d4d]",
  "reminder-form__actions": "flex justify-end gap-1.5 pt-0.5",
  "reminder-cancel": "min-h-8 px-2.5 text-[9px]",
  "reminder-form__hint": "m-0 text-[10px] leading-6 text-[#6f7068]",
  "notification-settings": "mb-5 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4 rounded-2xl border border-[#dfded7] bg-white p-5 max-[700px]:grid-cols-1 [&_h2]:m-1 [&_h2]:text-[15px] [&_h2]:font-extrabold [&_p]:m-1 [&_p]:text-[10px] [&_p]:leading-5 [&_p]:text-[#77786f]",
  "notification-settings__message": "col-span-full m-0 text-[10px] text-[#6f7068]",
  /* landing */
  "landing-shell": "overflow-hidden bg-[#151511] font-sans text-[#f8f8f2]",
  "landing-container": "mx-auto w-[min(1180px,calc(100%-40px))]",
  "landing-nav-wrap": "absolute inset-x-0 top-0 z-30",
  "landing-nav": "mx-auto grid min-h-[78px] w-[min(1180px,calc(100%-40px))] grid-cols-[1fr_auto_1fr] items-center gap-6 border-b border-white/10",
  "landing-brand": "inline-flex items-center gap-2.5 text-[18px] font-extrabold tracking-[-0.05em] text-[#f8f8f2]",
  "rakhlo-wordmark-mark": "inline-flex h-7 w-7 items-center justify-center gap-[3px] rounded-[9px] bg-[#f8f8f2] p-1.5 [&_span]:h-full [&_span]:min-w-[3px] [&_span]:flex-1 [&_span]:rounded-full [&_span]:bg-[#151511] [&_span:last-child]:min-w-[5px] [&_span:last-child]:flex-none [&_span:last-child]:bg-[#c9f36e]",
  "landing-nav-links": "flex items-center justify-center gap-7 text-[11px] font-semibold text-[#9b9b92] [&_a]:transition [&_a]:hover:text-[#f8f8f2]",
  "landing-nav-actions": "flex items-center justify-self-end gap-2",
  "landing-login": "px-3 py-2 text-[11px] font-semibold text-[#a8a8a0] hover:text-white",
  "landing-nav-cta": "inline-flex min-h-9 items-center justify-center gap-2 rounded-lg bg-[#f8f8f2] px-3.5 text-[10px] font-extrabold text-[#151511] shadow-[0_8px_20px_rgba(0,0,0,0.15)] hover:bg-white",
  "landing-language": "inline-flex min-h-9 min-w-[74px] items-center justify-center gap-0.5 rounded-full border border-white/15 bg-white/5 p-0.5 text-[9px] font-bold text-[#f8f8f2] [&_span]:grid [&_span]:h-7 [&_span]:min-w-[30px] [&_span]:place-items-center [&_span]:rounded-full [&_span]:px-1.5 [&_span]:text-[#9b9b92] [&_span.is-active]:bg-white [&_span.is-active]:text-[#151511]",
  "landing-hero": "border-b border-white/10 bg-[#151511] pt-[118px]",
  "landing-hero-inner": "mx-auto grid min-h-[670px] w-[min(1180px,calc(100%-40px))] grid-cols-[0.92fr_1.08fr] items-center gap-16 pb-20",
  "landing-hero-copy": "relative z-10 max-w-[680px] [&_h1]:m-0 [&_h1]:mt-4 [&_h1]:max-w-[720px] [&_h1]:text-[clamp(48px,6.8vw,86px)] [&_h1]:font-extrabold [&_h1]:leading-[0.96] [&_h1]:tracking-[-0.07em] [&_h1]:text-[#f8f8f2] [&_h1_em]:not-italic [&_h1_em]:text-[#c9f36e] [&_p]:mt-6 [&_p]:max-w-[600px] [&_p]:text-[14px] [&_p]:leading-7 [&_p]:text-[#a6a69d]",
  "landing-eyebrow": "inline-flex items-center gap-2 text-[9px] font-extrabold uppercase tracking-[0.11em] text-[#aaa9a1]",
  "landing-eyebrow-pulse": "h-1.5 w-1.5 rounded-full bg-[#c9f36e] shadow-[0_0_0_6px_rgba(201,243,110,0.1)]",
  "landing-hero-actions": "mt-7 flex flex-wrap gap-2.5",
  "landing-button": "inline-flex min-h-11 items-center justify-center gap-2 rounded-[10px] px-4 text-[11px] font-extrabold transition hover:-translate-y-0.5",
  "landing-button-dark": "bg-[#f8f8f2] text-[#151511] shadow-[0_10px_24px_rgba(0,0,0,0.15)] hover:bg-white",
  "landing-button-light": "border border-white/15 bg-white/5 text-[#f8f8f2] hover:bg-white/10",
  "landing-button-lime": "bg-[#c9f36e] text-[#151511]",
  "landing-hero-note": "mt-4 inline-flex items-center gap-2 text-[10px] text-[#8f8f87]",
  "landing-hero-visual": "min-h-[550px] grid place-items-center",
  "landing-product-scene": "relative min-h-[560px] w-full max-w-[650px]",
  "landing-scene-grid": "absolute inset-0 rounded-[28px] border border-white/10 bg-[linear-gradient(rgba(255,255,255,0.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.035)_1px,transparent_1px)] bg-[size:32px_32px]",
  "landing-product-window": "absolute left-[6%] top-[8%] z-10 w-[88%] overflow-hidden rounded-[18px] border border-white/10 bg-[#fbfbf7] text-[#171713] shadow-[0_30px_80px_rgba(0,0,0,0.35)] [transform:perspective(1200px)_rotateY(-5deg)_rotateX(1deg)] [animation:landing-window-in_650ms_ease-out_both]",
  "landing-window-top": "flex h-10 items-center justify-between border-b border-[#e6e5de] bg-white px-3.5",
  "landing-window-brand": "inline-flex items-center gap-2 text-[11px] font-extrabold tracking-[-0.04em] [&_.rakhlo-wordmark-mark]:h-5 [&_.rakhlo-wordmark-mark]:w-5 [&_.rakhlo-wordmark-mark]:rounded-md [&_.rakhlo-wordmark-mark]:p-1",
  "landing-window-dots": "flex items-center gap-1.5 [&_span]:h-1.5 [&_span]:w-1.5 [&_span]:rounded-full [&_span]:bg-[#d5d5cd]",
  "landing-window-body": "grid grid-cols-[54px_minmax(0,1fr)] min-h-[470px]",
  "landing-mini-sidebar": "flex flex-col items-center gap-3 border-r border-[#e6e5de] bg-[#f4f4ef] pt-5 [&_.landing-mini-dot]:h-6 [&_.landing-mini-dot]:w-6 [&_.landing-mini-dot]:rounded-[7px] [&_.landing-mini-dot]:bg-[#e2e2da] [&_.landing-mini-dot].active:bg-[#171713]",
  "landing-mini-dot": "",
  "landing-mini-main": "min-w-0 p-5",
  "landing-mini-header": "flex items-center justify-between gap-4 [&_strong]:mt-1 [&_strong]:block [&_strong]:text-[21px] [&_strong]:font-extrabold [&_strong]:tracking-[-0.04em]",
  "landing-mini-kicker": "text-[9px] font-extrabold uppercase tracking-[0.08em] text-[#9a9b93]",
  "landing-mini-avatar": "grid h-9 w-9 place-items-center rounded-full bg-[#171713] text-[11px] font-extrabold text-white",
  "landing-mini-search": "mt-5 flex items-center gap-2 rounded-xl bg-[#efeee8] px-3 py-2.5 text-[10px] text-[#96978f] [&_svg]:shrink-0 [&_kbd]:ml-auto [&_kbd]:rounded bg-white [&_kbd]:px-1.5 [&_kbd]:py-1 [&_kbd]:text-[8px]",
  "landing-memory-alert": "mt-4 grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2.5 rounded-2xl border border-[#d9e7cf] bg-[#eff9e9] p-3 [&>div:nth-child(2)]:min-w-0 [&>div:nth-child(2)_span]:block [&>div:nth-child(2)_span]:text-[8px] [&>div:nth-child(2)_span]:font-extrabold [&>div:nth-child(2)_span]:uppercase [&>div:nth-child(2)_span]:tracking-[0.08em] [&>div:nth-child(2)_span]:text-[#6a7162] [&>div:nth-child(2)_strong]:mt-0.5 [&>div:nth-child(2)_strong]:block [&>div:nth-child(2)_strong]:truncate [&>div:nth-child(2)_strong]:text-[11px] [&>div:nth-child(2)_small]:mt-0.5 [&>div:nth-child(2)_small]:block [&>div:nth-child(2)_small]:text-[9px] [&>div:nth-child(2)_small]:text-[#64705d]",
  "landing-memory-alert-icon": "grid h-9 w-9 place-items-center rounded-xl bg-white text-[#171713] shadow-[0_8px_20px_rgba(40,60,20,0.07)]",
  "landing-mini-section-head": "mt-5 flex items-center justify-between text-[9px] font-extrabold text-[#73746c]",
  "landing-mini-purchases": "mt-2 divide-y divide-[#ecebe5]",
  "landing-mini-purchase": "grid min-h-[70px] grid-cols-[34px_minmax(0,1fr)_auto] items-center gap-2.5",
  "landing-purchase-art": "grid h-8 w-8 place-items-center rounded-lg bg-[#e4e0cf] text-[10px] font-extrabold",
  "landing-float-card": "absolute z-20 flex max-w-[210px] items-center gap-2 rounded-xl border border-white/15 bg-white/95 p-2.5 text-[#171713] shadow-[0_18px_36px_rgba(0,0,0,0.22)] backdrop-blur-[10px] [animation:landing-float_5s_ease-in-out_infinite]",
  "landing-float-proof": "bottom-[11%] left-0",
  "landing-float-reminder": "right-0 top-[10%]",
  "landing-float-icon": "grid h-9 w-9 shrink-0 place-items-center rounded-[11px] bg-[#f3f3ee]",
  "is-green": "bg-[#eff9e9]",
  "landing-proof-strip": "grid grid-cols-4 border-b border-white/10 bg-[#1c1c17] px-[max(20px,calc((100vw-1180px)/2))]",
  "landing-editorial": "border-b border-[#2a2a24] bg-[#151511] py-[110px]",
  "landing-editorial-grid": "grid grid-cols-[minmax(0,1fr)_340px] items-end gap-[70px]",
  "landing-section-label": "text-[8px] font-extrabold uppercase tracking-[0.13em] text-[#96968e]",
  "landing-memory-section": "bg-[#f7f7f1] py-[112px] text-[#171713]",
  "landing-memory-heading": "grid grid-cols-[minmax(0,1fr)_320px] items-end gap-[70px] [&_h2]:m-0 [&_h2]:mt-[18px] [&_h2]:text-[clamp(45px,6vw,80px)] [&_h2]:font-extrabold [&_h2]:leading-[0.96] [&_h2]:tracking-[-0.065em] [&_p]:m-0 [&_p]:text-[13px] [&_p]:leading-7 [&_p]:text-[#77786f]",
  "landing-timeline": "relative mt-[68px] grid grid-cols-3",
  "landing-timeline-card": "relative pr-8 [&_.landing-timeline-icon]:relative [&_.landing-timeline-icon]:z-10 [&_h3]:mt-5 [&_h3]:text-[17px] [&_h3]:font-bold [&_p]:mt-1.5 [&_p]:max-w-[250px] [&_p]:text-[12px] [&_p]:leading-6 [&_p]:text-[#7c7d74]",
  "is-first": "",
  "landing-timeline-index": "relative z-10 mb-4 w-fit rounded-md border border-[#d9d9d1] bg-[#f7f7f1] px-1.5 py-1 text-[8px] font-extrabold tracking-[0.08em] text-[#8a8b82]",
  "landing-timeline-icon": "grid h-11 w-11 place-items-center rounded-xl border border-[#d8d8d0] bg-white shadow-[0_10px_22px_rgba(28,28,24,0.06)]",
  "landing-timeline-line": "absolute left-[63px] right-0 top-[111px] hidden h-px bg-[#d5d5cd] md:block",
  "landing-features": "border-t border-[#d8d8d0] bg-[#efefe8] py-[112px] text-[#171713]",
  "landing-section-heading": "max-w-[760px] [&_h2]:m-0 [&_h2]:mt-[18px] [&_h2]:text-[clamp(45px,6vw,80px)] [&_h2]:font-extrabold [&_h2]:leading-[0.96] [&_h2]:tracking-[-0.065em]",
  "landing-features-title": "text-balance",
  "landing-feature-table": "mt-[58px] border-t border-[#d8d8d0]",
  "landing-feature-number": "text-[9px] font-extrabold tracking-[0.08em] text-[#8a8b82]",
  "landing-how": "bg-[#f7f7f1] py-[120px] text-[#171713]",
  "landing-how-grid": "mt-[58px] grid grid-cols-3",
  "landing-cta": "bg-[#f7f7f1] pb-[120px] text-[#171713]",
  "landing-cta-card": "relative flex items-end justify-between gap-12 overflow-hidden rounded-[20px] bg-[#171713] p-16 text-[#f8f8f2] [&>div]:relative [&>div]:z-10 [&_h2]:m-0 [&_h2]:mt-[18px] [&_h2]:max-w-[760px] [&_h2]:text-[clamp(45px,6vw,80px)] [&_h2]:font-extrabold [&_h2]:leading-[0.96] [&_h2]:tracking-[-0.065em] [&_p]:mt-[18px] [&_p]:max-w-[550px] [&_p]:text-[13px] [&_p]:leading-7 [&_p]:text-[#9b9b92]",
  "landing-footer": "border-t border-[#d8d8d0] bg-[#ecece5] text-[#171713]",
  "landing-footer-top": "flex min-h-[190px] items-start justify-between gap-14 py-12",
  "landing-footer-brand": "[&_p]:mt-3.5 [&_p]:max-w-[330px] [&_p]:text-[11px] [&_p]:leading-6 [&_p]:text-[#77786f]",
  "landing-footer-links": "flex gap-6 pt-1 [&_a]:text-[11px] [&_a]:font-bold [&_a]:text-[#62635b] [&_a]:hover:text-[#171713]",
  "landing-footer-bottom": "flex min-h-[60px] items-center justify-between gap-5 border-t border-[#d8d8d0] text-[9px] text-[#888980]",
  "landing-language-option": "",
};

export function tw(value: string): string {
  return value
    .split(/\s+/)
    .filter(Boolean)
    .map((token) => styles[token] ?? "")
    .filter(Boolean)
    .join(" ");
}
